import { access, mkdir, readFile, rename, unlink, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { parseDaisoSnapshot } from "../lib/daiso-import";

const DAISO_SNAPSHOT_LABEL = "data/sources/daiso-seoul-2026-09-03.json";
const DAISO_CANDIDATE_LABEL = "data/candidates/daiso-seoul-candidate.json";
export const DAISO_SNAPSHOT_PATH = resolve(DAISO_SNAPSHOT_LABEL);
export const DAISO_GENERATED_PATH = resolve("lib/generated/daiso-places.ts");
const EXPECTED_DAISO_PLACE_COUNT = 251;
const APPROVED_DAISO_SNAPSHOT_RETRIEVED_AT = "2026-09-03T11:33:15.554Z";
const APPROVED_DAISO_SNAPSHOT_SHA256 = "76fc704197fb2d3496fac76bfa073c353595c9eab12ef4079e3e46a989a7660f";

async function writeTextAtomically(path: string, value: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  const temporaryPath = `${path}.${process.pid}.tmp`;
  try {
    await writeFile(temporaryPath, value, "utf8");
    await rename(temporaryPath, path);
  } catch (error) {
    await unlink(temporaryPath).catch(() => undefined);
    throw error;
  }
}

export async function runDaisoBuild(options: { inputPath?: string; outputPath?: string } = {}): Promise<{ published: number; withheld: number }> {
  const inputPath = options.inputPath ?? DAISO_SNAPSHOT_PATH;
  try {
    await access(inputPath, constants.R_OK);
  } catch {
    throw new Error(
      `Missing approved Daiso source snapshot: ${inputPath}. Run npm run collect:daiso-data to create ` +
      `${DAISO_CANDIDATE_LABEL}, then review, approve, and explicitly stage that candidate at ${DAISO_SNAPSHOT_LABEL}.`,
    );
  }

  const snapshotText = await readFile(inputPath, "utf8");
  const snapshot: unknown = JSON.parse(snapshotText);
  const result = parseDaisoSnapshot(snapshot, { mode: "officialProvisional" });
  const retrievedAt = (snapshot as { retrievedAt: string }).retrievedAt;
  if (retrievedAt !== APPROVED_DAISO_SNAPSHOT_RETRIEVED_AT) {
    throw new Error(
      `Daiso source snapshot retrievedAt must be ${APPROVED_DAISO_SNAPSHOT_RETRIEVED_AT}; received ${retrievedAt}`,
    );
  }
  if (result.published.length !== EXPECTED_DAISO_PLACE_COUNT) {
    throw new Error(
      `Expected exactly ${EXPECTED_DAISO_PLACE_COUNT} published Daiso stores, received ${result.published.length}`,
    );
  }
  const actualSha256 = createHash("sha256").update(snapshotText).digest("hex");
  if (actualSha256 !== APPROVED_DAISO_SNAPSHOT_SHA256) {
    throw new Error(
      `Daiso source snapshot must match approved SHA-256 ${APPROVED_DAISO_SNAPSHOT_SHA256}; received ${actualSha256}`,
    );
  }
  const source = `// AUTO-GENERATED by scripts/build-daiso-places.ts — do not edit by hand.\n` +
    `// Source: ${DAISO_SNAPSHOT_LABEL} (${result.published.length} published; ${result.withheld.length} withheld by verification gate).\n\n` +
    `import type { DaisoPlace } from "../daiso-import";\n\n` +
    `export const DAISO_PLACES: DaisoPlace[] = ${JSON.stringify(result.published, null, 2)};\n`;
  await writeTextAtomically(options.outputPath ?? DAISO_GENERATED_PATH, source);
  return { published: result.published.length, withheld: result.withheld.length };
}

const modulePath = fileURLToPath(import.meta.url);
const isMain = process.argv.slice(1).some((argument) => resolve(argument) === modulePath);
if (isMain) {
  runDaisoBuild()
    .then(({ published, withheld }) => console.log(`Wrote ${DAISO_GENERATED_PATH}: ${published} published, ${withheld} withheld`))
    .catch((error: unknown) => {
      console.error(error instanceof Error ? error.message : error);
      process.exitCode = 1;
    });
}
