import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  buildProvisionalPhotoPlaces,
  type AdosPhotoSourceRow,
} from "../lib/ados-photo-provisional";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE_PATH = join(ROOT, "data", "sources", "adropofseoul_places-2026-09-08.json");
const INVENTORY_PATH = join(ROOT, "data", "place-photo-source-inventory.json");
const ALIAS_PATH = join(ROOT, "data", "place-photo-aliases.json");
const OUTPUT_PATH = join(ROOT, "lib", "generated", "ados-photo-provisional-places.ts");

function readKnownPlaceIds(): Set<string> {
  const ids = new Set<string>();
  for (const relativePath of [
    "lib/data.ts",
    "lib/generated/creatrip-places.ts",
    "lib/generated/oliveyoung-places.ts",
    "lib/generated/ados-places.ts",
    "lib/generated/ados-photo-places.ts",
    "lib/generated/daiso-places.ts",
  ]) {
    const path = join(ROOT, relativePath);
    if (!existsSync(path)) continue;
    for (const match of readFileSync(path, "utf8").matchAll(/\bid:\s*"([^"]+)"/g)) {
      ids.add(match[1]);
    }
  }
  return ids;
}

const sourceRows = JSON.parse(readFileSync(SOURCE_PATH, "utf8")) as AdosPhotoSourceRow[];
const inventory = JSON.parse(readFileSync(INVENTORY_PATH, "utf8")) as {
  schemaVersion: number;
  sources: { sourcePlaceId: string; photos: number }[];
};
const aliasManifest = JSON.parse(readFileSync(ALIAS_PATH, "utf8")) as {
  schemaVersion: number;
  aliases: { sourcePlaceId: string; targetPlaceId: string }[];
};

if (inventory.schemaVersion !== 1 || aliasManifest.schemaVersion !== 1) {
  throw new Error("Unsupported owner-photo source manifest schema");
}

const places = buildProvisionalPhotoPlaces({
  sourceRows,
  sourcePlaceIds: inventory.sources.map((source) => source.sourcePlaceId),
  existingPlaceIds: readKnownPlaceIds(),
  aliases: new Map(aliasManifest.aliases.map((alias) => [alias.sourcePlaceId, alias.targetPlaceId])),
});

const output = `// GENERATED by scripts/build-ados-photo-provisional-places.ts — do not edit.
// Owner-photo venues admitted by explicit owner decision before exact pin
// verification. Every record is marked provisional and carries no fabricated
// rating, review count, price tier, hours, or English-support claim.

import type { Place } from "../data";

export const ADOS_PHOTO_PROVISIONAL_PLACES: Place[] = ${JSON.stringify(places, null, 2)};
`;

writeFileSync(OUTPUT_PATH, output);
console.log(`${places.length} provisional owner-photo places → ${OUTPUT_PATH}`);
