import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, rename, unlink, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  buildDaisoRankingDataset,
  DAISO_RANKING_SOURCE,
  parseDaisoRankingCsv,
  type DaisoRankingDataset,
} from "../lib/daiso-ranking-import";

export const DAISO_RANKING_GENERATED_PATH = resolve("lib/generated/daiso-ranking-products.ts");

function renderModule(dataset: DaisoRankingDataset): string {
  return `// AUTO-GENERATED by scripts/build-daiso-ranking.ts — do not edit by hand.\n` +
    `// Source: ${dataset.source.sourceFile} (${dataset.source.rowCount} rows; ${dataset.products.length} TOP20 union products).\n\n` +
    `export const DAISO_RANKING_DATA = ${JSON.stringify(dataset, null, 2)} as const;\n`;
}

export async function writeTextAtomically(path: string, value: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  const temporaryPath = `${path}.${process.pid}.${Date.now()}.${randomUUID()}.tmp`;
  try {
    await writeFile(temporaryPath, value, "utf8");
    await rename(temporaryPath, path);
  } catch (error) {
    await unlink(temporaryPath).catch(() => undefined);
    throw error;
  }
}

export async function runDaisoRankingBuild(options: {
  inputPath: string;
  outputPath?: string;
}): Promise<{ sourceRows: 3046; generatedProducts: 38 }> {
  if (!options.inputPath?.trim()) throw new Error("Daiso ranking build requires an explicit inputPath");
  const sourceBytes = await readFile(options.inputPath);
  const sourceSha256 = createHash("sha256").update(sourceBytes).digest("hex");
  if (sourceSha256 !== DAISO_RANKING_SOURCE.sha256) {
    throw new Error(`Daiso ranking source must match approved SHA-256 ${DAISO_RANKING_SOURCE.sha256}; received ${sourceSha256}`);
  }
  const rows = parseDaisoRankingCsv(sourceBytes.toString("utf8"));
  const dataset = buildDaisoRankingDataset(rows, sourceSha256);
  await writeTextAtomically(options.outputPath ?? DAISO_RANKING_GENERATED_PATH, renderModule(dataset));
  return { sourceRows: 3046, generatedProducts: 38 };
}

export function rankingInputFromCli(
  args: readonly string[],
  environment: Readonly<Record<string, string | undefined>>,
): string {
  const equalsArgument = args.find((argument) => argument.startsWith("--input="));
  if (equalsArgument) {
    const value = equalsArgument.slice("--input=".length).trim();
    if (value) return value;
  }
  const inputIndex = args.indexOf("--input");
  if (inputIndex >= 0 && args[inputIndex + 1]?.trim()) return args[inputIndex + 1];
  if (environment.DAISO_RANKING_INPUT?.trim()) return environment.DAISO_RANKING_INPUT;
  throw new Error("Provide the approved CSV with --input <path> or DAISO_RANKING_INPUT");
}

const modulePath = fileURLToPath(import.meta.url);
const isMain = process.argv.slice(1).some((argument) => resolve(argument) === modulePath);
if (isMain) {
  let inputPath: string;
  try {
    inputPath = rankingInputFromCli(process.argv.slice(2), process.env);
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
    inputPath = "";
  }
  if (inputPath) {
    runDaisoRankingBuild({ inputPath })
      .then(({ sourceRows, generatedProducts }) => {
        console.log(`${sourceRows} source rows; ${generatedProducts} generated products`);
      })
      .catch((error: unknown) => {
        console.error(error instanceof Error ? error.message : error);
        process.exitCode = 1;
      });
  }
}
